### ISSUE TITLE
Node12 deprecation

### ISSUE THREAD

**Issue by HardNorth** [OleksiyRudenko/gha-git-credentials#7]
Hi!
Thanks for the useful action. Unfortunately lately we started getting this warning:
>Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: oleksiyrudenko/gha-git-credentials

Could you please update Node.js on version 16?
Thank you!

**Comment by OleksiyRudenko** [comment]
@HardNorth thanks for heads-up. Will do over this weekend.
~~Could you please add a link to any workflow run log that mentions this warning?~~
Upd: have found all needed details.

**Comment by OleksiyRudenko** [comment]
Fixed by ac5b66bcf3873df4259c681d957d8c145980171f (tagged `v2.1.1`, `v2.1-latest`, `v2-latest`, `latest`)

Feel free opening a new issue if you believe the fix doesn't work as expected.
Additional context and details will be helpful to resolve.
